### ISSUE TITLE
Matpower parsing error - string "Inf" can not be parsed

### ISSUE THREAD

**Issue by KSepetanc** [lanl-ansi/PowerModels.jl#729]
Test case: case2383wp.m from the Matpower can not be parsed.

There should probably be some workaround mechanics for such cases when there is an +-inf as an input.

Log:
[error | InfrastructureModels]: parsing error, the matlab string "Inf" can not be parsed to Int64 data
ERROR: LoadError: parsing error, the matlab string "Inf" can not be parsed to Int64 data
Stacktrace:
 [1] error(::Memento.Logger, ::String) at C:\Users\karlo\.julia\packages\Memento\oMnS1\src\loggers.jl:437
 [2] check_type(::Type{T} where T, ::SubString{String}) at C:\Users\karlo\.julia\packages\InfrastructureModels\vQasf\src\io\matlab.jl:294
 [3] #59 at .\array.jl:0 [inlined]
 [4] iterate at .\generator.jl:47 [inlined]
 [5] collect_to! at .\array.jl:711 [inlined]
 [6] collect_to_with_first!(::Array{Int64,1}, ::Int64, ::Base.Generator{Array{SubString{String},1},InfrastructureModels.var"#59#64"}, ::Int64) at .\array.jl:689
 [7] collect(::Base.Generator{Array{SubString{String},1},InfrastructureModels.var"#59#64"}) at .\array.jl:670
 [8] _type_array(::Array{SubString{String},1}) at C:\Users\karlo\.julia\packages\InfrastructureModels\vQasf\src\io\matlab.jl:114
 [9] (::InfrastructureModels.var"#66#70"{Array{Any,1},Int64})(::Int64) at .\none:0
 [10] iterate at .\generator.jl:47 [inlined]
 [11] collect_to!(::Array{Array{T,1} where T,1}, ::Base.Generator{UnitRange{Int64},InfrastructureModels.var"#66#70"{Array{Any,1},Int64}}, ::Int64, ::Int64) at .\array.jl:711
 [12] collect_to!(::Array{Array{Int64,1},1}, ::Base.Generator{UnitRange{Int64},InfrastructureModels.var"#66#70"{Array{Any,1},Int64}}, ::Int64, ::Int64) at .\array.jl:719
 [13] collect_to_with_first!(::Array{Array{Int64,1},1}, ::Array{Int64,1}, ::Base.Generator{UnitRange{Int64},InfrastructureModels.var"#66#70"{Array{Any,1},Int64}}, ::Int64) at .\array.jl:689
 [14] collect(::Base.Generator{UnitRange{Int64},InfrastructureModels.var"#66#70"{Array{Any,1},Int64}}) at .\array.jl:670
 [15] _parse_matlab_data(::Array{SubString{String},1}, ::Int64, ::Char, ::Char) at C:\Users\karlo\.julia\packages\InfrastructureModels\vQasf\src\io\matlab.jl:189
 [16] _parse_matlab_matrix(::Array{SubString{String},1}, ::Int64) at C:\Users\karlo\.julia\packages\InfrastructureModels\vQasf\src\io\matlab.jl:123
 [17] parse_matlab_string(::String; extended::Bool) at C:\Users\karlo\.julia\packages\InfrastructureModels\vQasf\src\io\matlab.jl:43
 [18] _parse_matpower_string(::String) at C:\Users\karlo\.julia\packages\PowerModels\4hY7S\src\io\matpower.jl:128
 [19] #parse_matpower#1 at C:\Users\karlo\.julia\packages\PowerModels\4hY7S\src\io\matpower.jl:9 [inlined]
 [20] parse_file(::IOStream; import_all::Bool, validate::Bool, filetype::SubString{String}) at C:\Users\karlo\.julia\packages\PowerModels\4hY7S\src\io\common.jl:19
 [21] #35 at C:\Users\karlo\.julia\packages\PowerModels\4hY7S\src\io\common.jl:10 [inlined]
 [22] open(::PowerModels.var"#35#36"{Bool,Bool,String}, ::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at .\io.jl:298
 [23] open at .\io.jl:296 [inlined]
 [24] #parse_file#34 at C:\Users\karlo\.julia\packages\PowerModels\4hY7S\src\io\common.jl:9 [inlined]
 [25] parse_file(::String) at C:\Users\karlo\.julia\packages\PowerModels\4hY7S\src\io\common.jl:9
 [26] top-level scope at C:\Users\karlo\OneDrive\gmsdir\OPF\pglib-opf\show_data.jl:5
in expression starting at C:\Users\karlo\OneDrive\gmsdir\OPF\pglib-opf\show_data.jl:5

**Comment by ccoffrin** [comment]
In general, the parser should be supporting `Inf` values, but adding an explicit test for this is a good idea.

https://github.com/lanl-ansi/InfrastructureModels.jl/issues/70

The key problem here is the bit  `the matlab string "Inf" can not be parsed to Int64 data`, which means there is a field in the file that PowerModels expects to be a discrete integer value but it was given the floating point value `Inf`.  Can you double check in the Matpower file where the inf occurs?

**Comment by KSepetanc** [comment]
From what I see it is put under Qmax and Qmin (`-inf`). It is 4th and 5th row in generator data. Qmax and min are float numbers so I don't see why inf is a problem.

I have found that there are multiple Matpower test cases that can not be parsed.
I think one of then didn't parse due to additional unexpected column, other had some functions at the end of the file for conversion of data from SI to p.u. (works once this is removed) while for third I did not jet establish a reason why it does not work.

Do you think that we should work to make all of them parsable?

**Comment by ccoffrin** [comment]
Can you send me an e-mail will the Matpower cases that do not work and I'll have a look.  Some features are not in scope of this parser (e.g. additional functions and programmatic data processing) but I would like to support as many as is reasonable.  I would like to get to the bottom of the `Inf` issue for sure.

As a side note, I can recomend using [PGLib-OPF](https://github.com/power-grid-lib/pglib-opf) as good source of transmission network data files in the Matpower format.  I know all of these work with PowerModels becouse I test these regularly.

**Comment by KSepetanc** [comment]
I have sent you an email with the cases.

I work frequently with PGLib-OPF. I mostly work with transmission grids and it is excellent. However, from time to time I have to deal with distribution grids as well. In Matpower cases there are some distribution networks like ieee33.

I think that there is a great scientific need for distribution cases repository. So far we have transmission OPF, transmission HVDC OPF and UC (not network constrained) benchmark repositories. What are your thoughts and plans on this?

**Comment by ccoffrin** [comment]
Thanks for pointing this out!  I had a look at the cases you sent along and here is a summary of what I found,
- case9Q.m, case30Q.m - a bug in data processing has been fixed; note, reactive power costs are ignored in PowerModels at the moment; OPF solves in both cases
- case33bw.m - data processing at the end is out of scope, parsing seems to work when this is removed; OPF finds infeasible point, most likely due to unit problems.
- case_RTS_GMLC.m - a bug in the generic matlab data parser, fixed in InfrastructureModels v0.5.3; OPF solves
- case_ACTIVSg200.m - working / or fixed by previous fixes; OPF solves
- case_ACTIVSg500.m - working / or fixed by previous fixes; OPF solves
- case2383wp.m - working / or fixed by previous fixes; OPF solves
- case_ACTIVSg2000.m - working / or fixed by previous fixes; OPF solves
- case_ACTIVSg10k.m - working / or fixed by previous fixes; OPF solves
- scenarios_ACTIVSg200.m, scenarios_ACTIVSg2000.m - not a Matpower case file and symbolic values are out of scope of the generic matpower parser

Currently, I am working on a tag of InfrastructureModels to address that bug.  Then I will merge a PR on PowerModels that resolves these issues and tag a new version of PowerModels.  Should happen in the next day or two.

> I think that there is a great scientific need for distribution cases repository. 

I agree with you about this, @sanderclaeys was working in this direction.  One specific point that has been a challenge in this regard is that there are some single-phase datasets out there that are being used for distribution level optimization; however single phase analysis does seem to have limited application in practice.  Hence, I believe distribution level OPF benchmarks should be on a multi-phase model.

**Comment by KSepetanc** [comment]
I have updated to the latest PowerModels master, but case_ACTIVSg_x cases still fail.
Is this due to InfrastructureModels not being updated still? Bellow is the log.

Thanks for the link on distribution cases.
I agree the distribution cases should be multi-phase. PGLib is very comprehensive, thus, I hope the work continues for distribution cases.

Log:
```
[warn | InfrastructureModels]: assignments are expected to be made to "chgtab" but given: chgtab = [
ERROR: LoadError: AssertionError: occursin(".", matrix_assignment)
Stacktrace:
 [1] _parse_matlab_data(::Array{SubString{String},1}, ::Int64, ::Char, ::Char) at C:\Users\karlo\.julia\packages\InfrastructureModels\BdnLM\src\io\matlab.jl:135
 [2] _parse_matlab_matrix(::Array{SubString{String},1}, ::Int64) at C:\Users\karlo\.julia\packages\InfrastructureModels\BdnLM\src\io\matlab.jl:123
 [3] parse_matlab_string(::String; extended::Bool) at C:\Users\karlo\.julia\packages\InfrastructureModels\BdnLM\src\io\matlab.jl:43
 [4] _parse_matpower_string(::String) at C:\Users\karlo\.julia\packages\PowerModels\LKwZi\src\io\matpower.jl:128
 [5] #parse_matpower#1 at C:\Users\karlo\.julia\packages\PowerModels\LKwZi\src\io\matpower.jl:9 [inlined]
 [6] parse_file(::IOStream; import_all::Bool, validate::Bool, filetype::SubString{String}) at C:\Users\karlo\.julia\packages\PowerModels\LKwZi\src\io\common.jl:19
 [7] #35 at C:\Users\karlo\.julia\packages\PowerModels\LKwZi\src\io\common.jl:10 [inlined]
 [8] open(::PowerModels.var"#35#36"{Bool,Bool,String}, ::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at .\io.jl:298
 [9] open at .\io.jl:296 [inlined]
 [10] #parse_file#34 at C:\Users\karlo\.julia\packages\PowerModels\LKwZi\src\io\common.jl:9 [inlined]
 [11] parse_file at C:\Users\karlo\.julia\packages\PowerModels\LKwZi\src\io\common.jl:9 [inlined]
 [12] top-level scope at C:\Users\karlo\OneDrive\gmsdir\OPF\pglib-opf\show_data_br.jl:12
in expression starting at C:\Users\karlo\OneDrive\gmsdir\OPF\pglib-opf\show_data_br.jl:10
```

**Comment by sanderclaeys** [comment]
@KSepetanc I couldn't agree more; instead of defining new cases ad-hoc for each paper/study, it would be great to have several well-defined cases for multi-phase OPF. I have some plans to work towards a few initial benchmarks like that, but not before the last months of this year.

It would be interesting if you can share which cases you think will be most interesting; some included features could be:
- loads: delta/wye connected, voltage dependent (ZIP, exponential)
- lines: multiconductor, with explicit neutral modelling vs Kron-reduced networks
- voltage constraints: limits on phase-to-neutral, phase-to-phase, neutral-to-ground (four-wire networks), voltage unbalance factor
- transformers: two-winding, lossy delta-wye transformers, split-phase transformers,...

**Comment by ccoffrin** [comment]
@KSepetanc, that is the kind of error that I get when trying to load one of these files `scenarios_ACTIVSg200.m`, `scenarios_ACTIVSg2000.m`, which are out of scope of this parser.  The case files `case_ACTIVSg200.m, ...` should be working, can you double check those?

**Comment by KSepetanc** [comment]
@ccoffrin you are right, I made a mistake. I run the "contab_ACTIVSg_num" cases which also have symbolic values and not "case_ACTIVSg_num" as stated.

@sanderclaeys I am mostly working on transmission systems so my thoughts may not be fully relevant or correct.

US and Europe distribution network structures are somewhat different.
For Europe, on medium voltage level loads are mostly represented as delta since they are connected through their own transformer of delta-wye type. On low voltage level, there are both types of loads. I would say that exponential voltage dependency should be a priority. It is easier to obtain parameters for that type.

I can not make recommendations regarding line modeling.

Voltage phase-to-neutral should be by far the most important voltage constraint.

In Europe delta-wye and two-winding transformers are priority. Split-phase are almost non-existent.
